### PR TITLE
Issue 1771: fix number inputs for badge and zipcode on IE 11

### PR DESCRIPTION
**Pull request by Niicck**
cityofaustin/techstack#1771

Primarily concerning
- badge numbers for officers
- zip code for about-you

Browser:
Windows 10, IE 11

Link to pr deployment:
https://opo.austintexas.io/police-complain/1771-badge/

QA Test Criteria:
1. Fill out form with a police badge number and a zip code in the about you page.
2. Check that those numbers show up on the review page.
3. Make sure you can edit those numbers on the review page.
4. Send a confirmation email to yourself.
5. Make sure the confirmation email contains the numbers you entered.

Once this Review/QA is confirmed, then we'll merge it into master and close this issue.

### CODE REVIEW

**Comment by easherma** [comment]
FYI: IE11 handles number fields in weird ways when it comes to Javascript parsing

**Comment by desigonz** [comment]
Lookin good! Closing this one.

**Comment by desigonz** [comment]
Looks good!

**Comment by easherma** [comment]
@Niicck questions to answer at your leisure: 

1. Did you happen to look if importing this new dependency has any significant effects on the bundle size? 
2. Do you think we could avoid issues like this by using babel and more specifically defining our target browsers? Looking at https://babeljs.io/docs/en/babel-preset-env & https://babeljs.io/docs/en/babel-polyfill

**Pull request merged**
